# 1. Builder
FROM node:20-alpine AS builder
WORKDIR /app

COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

# 2. Runner
FROM node:20-alpine AS runner
WORKDIR /app

# Copy package để chạy `npm ci --omit=dev` (tùy chọn)
COPY --from=builder /app/package*.json ./
RUN npm ci --omit=dev

# Copy build output
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public

EXPOSE 3000
CMD ["npm", "start"]
