version: "3.8"
services:
  backend:
    image: ngthanhhoangphuc/my-fullstack-backend:latest
    container_name: backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_USERNAME=mysql
      - DB_PORT=3306
      - DB_USERNAME=app_user
      - DB_PASSWORD=12345678
      - DB_DATABASE=Deploy_DB
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mysql
      - redis

  frontend:
    image: ngthanhhoangphuc/my-fullstack-frontend:latest
    container_name: frontend
    ports:
      - "8080:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: Deploy_DB
      MYSQL_USER: app_user
      MYSQL_PASSWORD: 12345678
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
