services:
  backend:
    build:
      context: ./Backend
    container_name: backend
    ports:
      - "3000:3000"  # Cổng backend
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=123456abc
      - MYSQL_HOST=mysql
      - MYSQL_PORT=3306
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=12345678
      - MYSQL_DATABASE=Deploy_DB
    depends_on:
      - redis
      - mysql
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend
    container_name: frontend
    ports:
      - "8080:3000"  # Cổng frontend
    depends_on:
      - backend
    environment:
      - NODE_ENV=production
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_PASSWORD=123456abc
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=Deploy_DB
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=12345678
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  redis_data:
  mysql_data:
  